Website = "https://github.com/essentialist-app/essentialist"

[Details]
  Icon = "essentialist-icon.png"
  Name = "Essentialist"
  ID = "io.github.essentialist_app.essentialist"
  Version = "0.2.9"
  Build = 1
