Website = "https://essentialist.app"

[Details]
  Icon = "flatpak/io.github.essentialist_app.essentialist.png"
  Name = "Essentialist"
  ID = "io.github.essentialist_app.essentialist"
  Version = "0.3.12"
  Build = 1
[Migrations]
  fyneDo = true
