Website = "https://github.com/essentialist-app/essentialist"

[Details]
  Icon = "essentialist-icon.png"
  Name = "Essentialist"
  ID = "com.github.essentialist-app.essentialist"
  Version = "0.2.7"
  Build = 61
