name: Build Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_call:
    inputs:
      tag:
        description: 'The git tag to create a release for.'
        required: false
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets: inherit

  create-release:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifcats
        uses: actions/download-artifact@v4

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag || github.ref_name }}
          artifacts: "Essentialist for Linux/essentialist-linux,Essentialist for Linux (flatpak)/essentialist.flatpak,Essentialist for Windows/essentialist.exe,Essentialist for MacOS/Essentialist.dmg,Essentialist for Android (APK)/Essentialist.apk"
