name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.2.3)'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          sed -i -e 's/[0-9]\+\.[0-9]\+\.[0-9]\+/'${{ inputs.version }}'/' \
              cmd/essentialist/FyneApp.toml \
              cmd/essentialist/about.go \
              cmd/essentialist/flatpak/io.github.essentialist_app.essentialist.metainfo.xml \
              cmd/essentialist/flatpak/io.github.essentialist_app.essentialist.yml

      - name: Commit and push version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'v${{ inputs.version }}'
          branch: main
          file_pattern: 'cmd/essentialist/FyneApp.toml cmd/essentialist/about.go cmd/essentialist/flatpak/io.github.essentialist_app.essentialist.metainfo.xml cmd/essentialist/flatpak/io.github.essentialist_app.essentialist.yml'

  build-artifacts:
    needs: update-version
    uses: ./.github/workflows/build-artifacts.yml
    secrets: inherit

  create-tag-and-release:
    needs: [update-version, build-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the commit created by the update-version job
          ref: 'main'

      - name: Create and push tag
        run: |
          git tag v${{ needs.update-version.outputs.version }}
          git push origin v${{ needs.update-version.outputs.version }}

      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.update-version.outputs.version }}
          artifacts: "artifacts/Essentialist for Linux/essentialist-linux,artifacts/Essentialist for Linux (flatpak)/essentialist.flatpak,artifacts/Essentialist for Windows/essentialist.exe,artifacts/Essentialist for MacOS/Essentialist.dmg,artifacts/Essentialist for Android (APK)/Essentialist.apk"
          allowUpdates: true